eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    service-url: 
      defaultZone: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9010/eureka/
spring:
  datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql:aws://demodb.cluster-c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/test
    username: admin
    password: cB7mcvZH78XWRrMW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
