eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    service-url: 
      defaultZone: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9010/eureka/
spring:
  datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql:aws://cms-db-demo-3-instance-1.c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/cmsdbdemo3
    username: admin
    password: dRodemuspeNu6R9w
    #url: jdbc:mysql:aws://cmsdb-instance-1.c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/test
    #username: admin
    #password: keSDW95KuzvQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
feign:
   request:
      patientEntrollementUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/patientenrollment
      carePlanUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/careplan
      notificationUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/notification
      inboundIntegrationUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/inboundintegration
      authenticationUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/authentication
      administrationUrl: cms-demo-2039394018.ap-south-1.elb.amazonaws.com/administration