eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    service-url: 
      defaultZone: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9010/eureka/
spring:
  datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql:aws://cmsdb-instance-1.c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/test
    username: admin
    password: keSDW95KuzvQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
feign:
   request:
      patientEntrollementUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9008
      carePlanUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9006
      notificationUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9007
      inboundIntegrationUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9005
      authenticationUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9003
      administrationUrl: http://cms-loadbalancer-test-3-200805129.ap-south-1.elb.amazonaws.com:9002 
logging:
  file:
    path: ./target/logs/
    name: ${logging.file.path}${spring.application.name}.log

management:
  endpoint:
    logfile:
      external_file: ${logging.file.path}${spring.application.name}.log
  endpoints:
    web:
      exposure:
        include: '*'