eureka: 
  client: 
    service-url: 
      defaultZone: http://65.0.183.240:8761/eureka/
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:aurora//cmsdb-instance-1.c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/test
    username: admin
    password: keSDW95KuzvQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
    database-platform: org.hibernate.dialect.MariaDB53Dialect
