spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:aurora//cmsdb-instance-1.c0tyovlbd7c2.ap-south-1.rds.amazonaws.com:3306/cmsdb
    username: admin
    password: keSDW95KuzvQ 
    